// Enhanced AiModelsData.js with categories, descriptions, and last updated dates
const AiModelsData = [
    {
        id: 1,
        title: "ChatGPT",
        modelCount: 6,
        monthlyActiveUsers: 180,
        thumbnail: null,
        category: "chat",
        description: "OpenAI's flagship conversational AI assistant with multiple models including GPT-3.5 and GPT-4.",
        lastUpdated: "2025-01-15",
        features: ["Text generation", "Content summarization", "Code assistance", "Creative writing"],
        provider: "OpenAI",
        website: "https://chat.openai.com"
    },
    {
        id: 2,
        title: "Claude",
        modelCount: 4,
        monthlyActiveUsers: 20,
        thumbnail: null,
        category: "chat",
        description: "Anthropic's AI assistant focused on helpfulness, harmlessness, and honesty with long context windows.",
        lastUpdated: "2025-02-01",
        features: ["Constitutional AI", "Long context", "Document analysis", "Reasoning"],
        provider: "Anthropic",
        website: "https://claude.ai"
    },
    {
        id: 3,
        title: "DeepSeek",
        modelCount: 4,
        monthlyActiveUsers: 3.5,
        thumbnail: null,
        category: "chat",
        description: "Advanced open-source large language models with strong reasoning and coding capabilities.",
        lastUpdated: "2025-01-28",
        features: ["Code generation", "Mathematics", "Open source", "Multi-lingual"],
        provider: "DeepSeek AI",
        website: "https://deepseek.ai"
    },
    {
        id: 4,
        title: "Copilot",
        modelCount: 4,
        monthlyActiveUsers: 15,
        thumbnail: null,
        category: "specialized",
        description: "Microsoft and GitHub's AI-powered code completion and generation tool integrated with VS Code.",
        lastUpdated: "2024-12-10",
        features: ["Code completion", "Function generation", "Documentation", "Code explanation"],
        provider: "Microsoft/GitHub",
        website: "https://github.com/features/copilot"
    },
    {
        id: 5,
        title: "Midjourney",
        modelCount: 6,
        monthlyActiveUsers: 8,
        thumbnail: null,
        category: "images",
        description: "Text-to-image AI system capable of producing highly detailed and artistic visual content.",
        lastUpdated: "2025-01-05",
        features: ["Photorealistic images", "Artistic styles", "High resolution", "Concept visualization"],
        provider: "Midjourney",
        website: "https://www.midjourney.com"
    },
    {
        id: 6,
        title: "Qwen",
        modelCount: 13,
        monthlyActiveUsers: 5,
        thumbnail: null,
        category: "chat",
        description: "Alibaba's foundation models optimized for Chinese and English languages with strong reasoning.",
        lastUpdated: "2024-11-18",
        features: ["Multi-modal", "Bilingual optimization", "Knowledge encoding", "Enterprise integration"],
        provider: "Alibaba",
        website: "https://qwen.ai"
    },
    {
        id: 7,
        title: "Mistral",
        modelCount: 3,
        monthlyActiveUsers: 4,
        thumbnail: null,
        category: "chat",
        description: "Efficient open-source language models with strong performance-to-parameter ratio.",
        lastUpdated: "2025-02-10",
        features: ["Efficient architecture", "Strong reasoning", "Open weights", "Competitive performance"],
        provider: "Mistral AI",
        website: "https://mistral.ai"
    },
    {
        id: 8,
        title: "Llama",
        modelCount: 3,
        monthlyActiveUsers: 6,
        thumbnail: null,
        category: "chat",
        description: "Meta's open foundation models designed for researchers and commercial applications.",
        lastUpdated: "2024-12-05",
        features: ["Open weights", "Adaptable", "Research-focused", "Multiple size variants"],
        provider: "Meta AI",
        website: "https://llama.meta.com"
    },
    {
        id: 9,
        title: "DALL-E",
        modelCount: 1,
        monthlyActiveUsers: 12,
        thumbnail: null,
        category: "images",
        description: "OpenAI's text-to-image generation model capable of creating detailed visual content from descriptions.",
        lastUpdated: "2025-01-25",
        features: ["Photorealistic images", "Concept visualization", "Style adaptation", "Outpainting"],
        provider: "OpenAI",
        website: "https://openai.com/dall-e-3"
    },
    {
        id: 10,
        title: "Grok",
        modelCount: 2,
        monthlyActiveUsers: 3,
        thumbnail: null,
        category: "chat",
        description: "xAI's conversational model with real-time knowledge and a sense of humor.",
        lastUpdated: "2025-01-20",
        features: ["Real-time data", "Web browsing", "Coding assistance", "Humor"],
        provider: "xAI",
        website: "https://grok.x.ai"
    },
    {
        id: 11,
        title: "Gemma",
        modelCount: 2,
        monthlyActiveUsers: 2,
        thumbnail: null,
        category: "chat",
        description: "Google DeepMind's lightweight open-source models for developers to build with.",
        lastUpdated: "2025-02-06",
        features: ["Efficient inference", "Open weights", "Developer-focused", "Mobile compatibility"],
        provider: "Google DeepMind",
        website: "https://blog.google/technology/ai/google-gemma-open-model/"
    },
    {
        id: 12,
        title: "Gemini",
        modelCount: 3,
        monthlyActiveUsers: 25,
        thumbnail: null,
        category: "chat",
        description: "Google's multimodal AI system designed to understand, operate across and combine text, images, audio, video, and code.",
        lastUpdated: "2025-01-30",
        features: ["Multimodal", "Reasoning", "Google integration", "Advanced math"],
        provider: "Google",
        website: "https://deepmind.google/technologies/gemini/"
    },
    {
        id: 13,
        title: "Sora",
        modelCount: 1,
        monthlyActiveUsers: 0.8,
        thumbnail: null,
        category: "video",
        description: "OpenAI's text-to-video model capable of generating realistic and creative video content from text prompts.",
        lastUpdated: "2025-02-15",
        features: ["High fidelity video", "Long sequences", "Physics understanding", "Camera movements"],
        provider: "OpenAI",
        website: "https://openai.com/sora"
    },
    {
        id: 14,
        title: "Whisper",
        modelCount: 2,
        monthlyActiveUsers: 5,
        thumbnail: null,
        category: "voice",
        description: "OpenAI's speech recognition system trained on diverse audio that can transcribe and translate spoken language.",
        lastUpdated: "2024-11-05",
        features: ["Multilingual transcription", "Robust to accents", "Translation", "Background noise handling"],
        provider: "OpenAI",
        website: "https://openai.com/research/whisper"
    },
    {
        id: 15,
        title: "Stable Diffusion",
        modelCount: 5,
        monthlyActiveUsers: 7,
        thumbnail: null,
        category: "images",
        description: "Stability AI's open-source text-to-image models with variants for different visual styles and applications.",
        lastUpdated: "2025-01-10",
        features: ["Open source", "User fine-tuning", "Multiple variants", "Local deployment"],
        provider: "Stability AI",
        website: "https://stability.ai/stable-diffusion"
    },
    {
        id: 16,
        title: "AudioCraft",
        modelCount: 3,
        monthlyActiveUsers: 1.2,
        thumbnail: null,
        category: "voice",
        description: "Meta's AI system for generating high-quality audio and music from text descriptions.",
        lastUpdated: "2024-12-20",
        features: ["Music generation", "Sound effects", "Voice synthesis", "Extended compositions"],
        provider: "Meta AI",
        website: "https://audiocraft.metademolab.com"
    },
    {
        id: 17,
        title: "NeRF",
        modelCount: 4,
        monthlyActiveUsers: 0.5,
        thumbnail: null,
        category: "3d",
        description: "Neural Radiance Fields technology for creating 3D scenes from 2D images with various implementations.",
        lastUpdated: "2024-11-15",
        features: ["3D scene reconstruction", "View synthesis", "Photorealistic rendering", "Dynamic scenes"],
        provider: "Various",
        website: "https://www.matthewtancik.com/nerf"
    },
    {
        id: 18,
        title: "CodeLlama",
        modelCount: 3,
        monthlyActiveUsers: 4.5,
        thumbnail: null,
        category: "specialized",
        description: "Meta's code-focused LLM optimized for programming tasks across multiple languages.",
        lastUpdated: "2025-01-05",
        features: ["Multi-language coding", "Function completion", "Code explanation", "Bug fixing"],
        provider: "Meta AI",
        website: "https://ai.meta.com/blog/code-llama-2/"
    }
];

export default AiModelsData;